# Generated by Django 3.2.6 on 2021-09-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demogithub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='index',
        ),
    ]
