# Generated by Django 3.2.6 on 2021-09-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demogithub', '0002_remove_profile_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_updated',
        ),
    ]
