# Generated by Django 3.2.6 on 2021-09-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demogithub', '0004_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
