# Generated by Django 3.2.6 on 2021-09-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demogithub', '0005_profile_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
