# Generated by Django 3.2.6 on 2021-09-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demogithub', '0006_profile_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demogithub.profile'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='stars',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
